### ISSUE TITLE
pagination helper raises ArgumentError

### ISSUE THREAD

**Issue by snex** [kaminari/kaminari-sinatra#8]
```
 ArgumentError - wrong number of arguments (given 0, expected 3) (ArgumentError):
	.rvm/gems/ruby-3.2.1/gems/actionview-7.1.3/lib/action_view/base.rb:228:in `initialize'
	.rvm/gems/ruby-3.2.1/gems/kaminari-sinatra-1.0.1/lib/kaminari/helpers/sinatra_helpers.rb:30:in `initialize'
	.rvm/gems/ruby-3.2.1/gems/kaminari-sinatra-1.0.1/lib/kaminari/helpers/sinatra_helpers.rb:94:in `new'
	.rvm/gems/ruby-3.2.1/gems/kaminari-sinatra-1.0.1/lib/kaminari/helpers/sinatra_helpers.rb:94:in `paginate'
	views/index.erb:13:in `__tilt_1140'
```

I see no commits in 3 years. Is this project even still alive?

**Comment by yuki24** [comment]
We are still here. Could you provide an example that replicates your issue so we can look into it?

**Comment by snex** [comment]
Just merely doing a "<%= paginate @models %>" on a view seems to cause the error. However I have switched to pagy which seems to work so I won't be able to supply any further info.

It looks like the call to "super()" on line 30 of sinatra_helpers.rb is out of date compared to what action_view expects.
